apiVersion: batch/v1
kind: CronJob
metadata:
  name: docker-watcher
spec:
  schedule: "*/1 * * * *"  # Runs every 1 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: docker-watcher
            image: challavishwanath/docker-watcher:latest
            volumeMounts:
            - name: tag-storage
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: tag-storage
            hostPath:
              path: /tmp/docker-watcher
              type: DirectoryOrCreate
